# coding=utf-8
import mysql.connector


# Conexão com banco de dados
def ConectaBanco():
    """Ligação com banco de dados MySQL, inserir seu usuário e senha"""
    cnx = mysql.connector.connect(database='PROJETO_DEP', host='localhost', user='root', passwd='urpassword')
    cnx.autocommit = True
    return cnx


# Modelo físico do banco de dados em MySQL
""""
CREATE DATABASE PROJETO_DEP;
USE PROJETO_DEP;

#CRIACAO DA TABELA SOLICITANTES  
CREATE TABLE TB_SOLICITANTES(
EMAIL VARCHAR(100) NOT NULL,
SENHA VARCHAR(100) NOT NULL,
NOME VARCHAR(100),
CARGO VARCHAR(50),
PRIMARY KEY(EMAIL));

#CRIACAO DA TABELA TECNICOS
CREATE TABLE TB_TECNICOS(
EMAIL VARCHAR(100) NOT NULL,
SENHA VARCHAR(100) NOT NULL,
NOME VARCHAR(100),
CARGO VARCHAR(50),
PRIMARY KEY(EMAIL));

#CRIACAO DA TABELA SERVICOS
CREATE TABLE TB_SERVICOS(
ID_SERVICO INT NOT NULL AUTO_INCREMENT,
NOME VARCHAR(100),
DESCRICAO VARCHAR(100),
PRIMARY KEY(ID_SERVICO));

#CRIACAO DA TABELA ORDENS
CREATE TABLE TB_ORDENS(
ID_ORDEM INT NOT NULL AUTO_INCREMENT,
ID_SERVICO INT NOT NULL,
EMAIL_SOLICITANTE VARCHAR(100) NOT NULL,
EMAIL_TECNICO VARCHAR(100),
DATA_SOLICITACAO DATETIME NOT NULL,
DATA_INICIO DATETIME,
DATA_FIM DATETIME,
DESCRIÇÃO VARCHAR(200),
URGENCIA INT NOT NULL,
LOCAL_ATENDIMENTO VARCHAR(100),
FEEDBACK VARCHAR(1000),
NOTA INT,
FOREIGN KEY(ID_SERVICO) REFERENCES TB_SERVICOS(ID_SERVICO),
FOREIGN KEY(EMAIL_SOLICITANTE) REFERENCES TB_SOLICITANTES(EMAIL),
FOREIGN KEY(EMAIL_TECNICO) REFERENCES TB_TECNICOS(EMAIL),
PRIMARY KEY(ID_ORDEM));

# Inserção de serviços básicos
INSERT INTO TB_SERVICOS (NOME) 
VALUES ('Manutenção de impressoras'),('Manutenção de projetores'),('Troca de HD'),
('Instalação de software'),('Manutenção de computadores'),('Formatar computador');
"""
